### ISSUE TITLE
[FEATURE] Allow "default" behavior, e.g. allow setting for job to succeed without matching label

### ISSUE THREAD

**Issue by logyball** [zwaldowski/match-label-action#23]
Hello! This GH action is awesome and I'm interested in using it for a couple of projects I'm working on.  It is especially helpful for matching semver labels to determine how to bump project version using PRs (as documented in your other action, [semver-release-action](https://github.com/zwaldowski/semver-release-action) ).  

A feature that I would really love is the ability for an option for users to toggle a "default" behavior if a label isn't found that is not a simple pipeline failure.  I could see this working one of two ways:
1. Default Label - i.e. pick a label that will be used throughout the pipeline as the "match" even if it does not appear on the PR
2. Fail if match is not found - i.e. a boolean setting that if true, exits with an error if a label is not found (the current behavior) and, if false, exits with a warning if a label is not found.

Anyways, if either of those sound like fun to you, I'd be more than happy to implement them.

Thanks

**Comment by zwaldowski** [comment]
Sounds cool to me. PRs welcome.

**Comment by logyball** [comment]
Opened PR #24 @zwaldowski

**Comment by zwaldowski** [comment]
Closed via #24
